### ISSUE TITLE
splitfolders.ratio fail without error message

### ISSUE THREAD

**Issue by leminhds** [jfilter/split-folders#27] opened 2021-08-03 06:54 UTC
I have correctly implemented splitfolders.ratio(input= input_folder, 
                       output=output_folder, seed=1337, ratio=(.9, 0.1))

There is no error message. However, the files are not split and remain in the input folder. the output folder does not change either. happens to python 3.9

**Comment by waterflyer** [comment] 2022-01-19 18:19
ok, I just found the right way to use it, you need to create a subfolder under your "output_folder" folder, such as "data", then after you executed the program, it will generate 3 folders that are test, train and val under your output folder, and inside those 3 folders, it will create a subfolder named "data" as well, and finally it will contain the images after the splitting as your specified ratio.

**Comment by jfilter** [comment] 2022-01-30 16:26
This is a duplicate of #13.

**Closed by jfilter** 2022-01-30 16:26 UTC
