### ISSUE TITLE
Assertion Error

### ISSUE THREAD

**Issue by vishal-prgmr** [jfilter/split-folders#5] opened 2019-04-26 14:23 UTC
I get this error when i use the **fixed** attribute. 
Error:

AssertionError                            Traceback (most recent call last)
<ipython-input-13-04a372b16923> in <module>
----> 1 split_folders.fixed('C:/Users/TEXVNQA/Downloads/TL_DATA/', output="C:/Users/TEXVNQA/Downloads/GTS_Torch Format/", seed=1337, fixed=(135,135), oversample=False) # default values

c:\torch\lib\site-packages\split_folders\split.py in fixed(input, output, seed, fixed, oversample)
     69     lens = []
     70     for class_dir in dirs:
---> 71         lens.append(split_class_dir_fixed(class_dir, output, fixed, seed))
     72 
     73     if not oversample:

c:\torch\lib\site-packages\split_folders\split.py in split_class_dir_fixed(class_dir, output, fixed, seed)
    105     files = setup_files(class_dir, seed)
    106 
--> 107     assert len(files) > sum(fixed)
    108 
    109     split_train = len(files) - sum(fixed)

AssertionError:

**Comment by jfilter** [comment] 2019-04-26 14:25
How many items to you have as input?

**Comment by vishal-prgmr** [comment] 2019-04-26 14:33
I have 43 classes. And the classes are unballanced. The total number of images would be 1200.

**Comment by jfilter** [comment] 2019-04-26 14:38
So I assume for some classes, there are fewer than 135 samples? Can you try to turn oversampling on?

**Comment by jfilter** [comment] 2019-04-27 12:31
Just let me know if this was the cause for your problem. I agree that the error message was not useful and I could improve it.

**Comment by doursand** [comment] 2019-05-05 16:11
hello , first of all thanks for the great job, the tool is awesome :-)
I am experiencing the same issue with my unbalanced dataset. If I set the fixed param to a value above the maximum amount of files for one of the class i have the assertion error , and this even if i enable the oversample parameter.

**Comment by jmtzt** [comment] 2019-05-08 20:52
I am having the same issue, when I try to use

import split_folders

split_folders.fixed('/content/Data', output = "output", seed = 1337, fixed = (275, 275), oversample = True)

AssertionError                            Traceback (most recent call last)
<ipython-input-48-d9e5588c9bdf> in <module>()
      1 import split_folders
      2 
----> 3 split_folders.fixed('/content/Data', output = "output", seed = 1337, fixed = (275, 275), oversample = True)

1 frames
/usr/local/lib/python3.6/dist-packages/split_folders/split.py in split_class_dir_fixed(class_dir, output, fixed, seed)
    105     files = setup_files(class_dir, seed)
    106 
--> 107     assert len(files) > sum(fixed)
    108 
    109     split_train = len(files) - sum(fixed)

AssertionError: 

I have 28 folders which are my classes and the max amount of images in one class is 275, that's why the fixed of (275, 275). What should I do?

**Comment by jfilter** [comment] 2019-05-12 12:55
Okay people, I improved the error message. Use a `ratio` instead of `fixed` if the number of samples are to few.

The problem is that I don't want to encourage over-sampling for the validation and test set. So if only 10 files exists and you want to use fixed with, i.e.,  (8, 8),  it's impossible. So I raise an error. The error message was not very helpful, though.

**Closed by jfilter** 2019-05-12 12:55 UTC

**Comment by iam8github** [comment] 2020-11-01 11:50
Hey @jfilter ,

First of all, let me admire your efforts for making our lives so easy by developing this very handy tool. However, there is problem for imbalanced number of files in folders. In my case I want to keep exactly 200 files for training and rest for the test/validation regardless of how many files left for test/validation. If I do so following your code guidelines;

To only split into training and validation set, use a single number to fixed, i.e., 10.
I got the following assertion error. Could you please help me to resolve this issue.

TypeError Traceback (most recent call last)
in ()
7
8 #no_files
----> 9 sp.fixed(data_dir, output=output_dir, seed=13, fixed=200, oversample=False, group_prefix=None) # default values

/usr/local/lib/python3.6/dist-packages/splitfolders/split.py in fixed(input, output, seed, fixed, oversample, group_prefix)
96 fixed = fixed
97
---> 98 assert len(fixed) in (1, 2)
99
100 if tqdm_is_installed:

TypeError: object of type 'int' has no len()
